### ISSUE TITLE
Add behat reports for CI

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/drevops#626]
```
default:
  formatters:
    pretty: ["std"]
    # progress: ~
    junit:
      output_path: "reports"
```
